[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "workshop-machine-learning-for-beginners"
version = "0.1.0"

authors = ["Alexander Hess <alexander@webartifex.biz>"]
description = "An introductory workshop on machine learning"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

jupyterlab = "^2.2.8"
matplotlib = "^3.3.2"
numpy = "^1.19.2"
pandas = "^1.1.2"
scikit-learn = "^0.23.2"
